#!/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
PACKAGES=$( dpkg --get-selections | grep deinstall |sed 's/deinstall//g')
PACKAGESLIST=$(echo $PACKAGES)
apt-get autoremove -y
apt-get autoclean -y
apt-get purge $PACKAGESLIST -y
